### PR TITLE
Properly trim spaces using the new TextEditor.edit() callback

### LINKED ISSUE #24: trimOnSave trims _after_ save instead of before
I think this is what the problem is.

I have trimOnSave on, and when I hit save it does trim whitespace, but it modifies the file and I have to hit save again.

### PR DESCRIPTION
**Pull request by ameily**
This should fix #24  and #21 

It looks like the vscode API changed to where vscode wants all document edits to be performed on the `TextEditorEdit` object passed to the `TextEdit.edit()` callback. This PR adds support for trimming trailing spaces on both `TextEditorEdit` and `WorkspaceEdit` objects. The changes should not affect on-demand trimming operations.

### CODE REVIEW

**Comment by shardulm94** [comment]
Thanks @ameily for digging into this. Back when I wrote this extension, the VSCode extension API did not have a hook to modify the file before save. Hence, I relied on the after save hook to achieve this functionality. Over these years, the vscode extension API and the execution environment has changed significantly. This extension needs a major refactor to ensure that it follows current VSCode standards. Hence I am a little hesitant to push out a minor or a patch version now. I will try to find some time next week to see if I can refactor and also include this change.

**Comment by ameily** [comment]
@shardulm94 based on my research, I think the other parts of the extension look fine. You could switch to a pre-save hook, `willSaveTextDocument()`, however vscode only allows a total of 1.5 seconds for this hook to execute and the documentation isn't clear on how to delay the save operation while any hooks run. So, I think keeping the hook in `didSaveTextDocument()` makes sense, in my opinion.

Other trailing spaces extensions don't come close to the features in trailing-spaces, so I think you'd be ok performing a minor release. Plus, that'd mean I wouldn't need to run a local version of the extension, :+1:

**Comment by shardulm94** [comment]
@ameily I think 1.5 seconds should be good enough. I will time some executions and see how they perform. I had already switched to the `onWillSaveTextDocument()` in the `develop` branch. And this PR fixes the issues I have been facing to get the unit tests running locally. I made some good progress last night (mostly cleaning up my terrible code from 3 years ago), so I am feeling more confident now.

**Comment by shardulm94** [comment]
I ran some performance tests around 1.5 second limit.
- Was able to delete 30k trailing space regions in the file within the limit with `deleteModifiedLinesOnly` set to false
- The diff logic for `deleteModifiedLinesOnly` is slow and hence only able to delete 1k trailing space regions within the limit

Given the above numbers, I think moving to `onWillSaveTextDocument()` is relatively safe and it is better to adhere to the API provided by VSCode for the pre-save edits purpose. I incorporated parts of your PR (applying edits on `TextEditorEdit`) in the `develop` branch and initial tests suggest that things look good. You can also give it a try using the VSIX file here https://github.com/shardulm94/vscode-trailingspaces/releases/tag/v0.3.0-rc1

Note: This does not fix #21 entirely, because it seems like the `deleteModifiedLinesOnly` logic has always been incorrect and broken.

**Comment by ameily** [comment]
@shardulm94 I tested v0.3.0-rc1 and verified that the problem is fixed! I literally cannot develop without this extension so I'm excited for the next official release.

**Comment by shardulm94** [comment]
Closing as parts of this PR were incorporated in d74fdefa1a772759e436256fce3843adc78d3d2d

**Pull request closed without merging**
